### ISSUE TITLE
Where are the new releases?

### ISSUE THREAD

**Issue by TWiStErRob** [kobjects/kxml2#17]
I came here from https://mvnrepository.com/artifact/net.sf.kxml/kxml2/2.3.0 via http://kxml.sourceforge.net/ redirecting to https://github.com/stefanhaustein/kxml2. I can see last commit is 2.5.0 version change, where is that released?

**Comment by TWiStErRob** [comment]
Ah, you moved to jitpack? Why?

**Comment by stefanhaustein** [comment]
I don't think it's a move -- the jitpack release is official. The mvn repository was created by a third party.
